### ISSUE TITLE
Makefile BASEPATH error

### ISSUE THREAD

**Issue by shathaway** [XZES40/CS-Capstone-Project#15]
BASEPATH = /usr/local/apps/tex_live/current/bin/x86_64-linux/

This path is not found on the debian virtual machine for build tasks.

Steve Hathaway

**Comment by shathaway** [comment]
Programs found in /usr/bin are:
latex, bibtex, dvips, dvipdft, xdvi

A related file for processing Makefile related to: "IEEEtran*" is found in path:
/usr/share/texlive/texmf-dist/bibtex/bst/mciteplus/

Steve Hathaway

**Comment by pop** [comment]
@shathaway Thank you for bringing this up.

This repository is for the OSU Engineering program as the projects need to build for Kevin and Kirsten on the OSU Engineering server. Since it's only meant to build on the OSU ENGR servers, which host a recent version of LaTeX and common libraries at that describe basepath, we decided to hardcode this path instead of remotely.

The development VMs will **only** be used for C/C++ development and **not** LaTeX file development for this reason.

If you are following along by building the LaTeX in the VM I suggest either changing the Makefile in your local copy or symlink your LaTeX environment to that basepath location.

**Comment by shathaway** [comment]
I am able todo most LaTeX makes by redefining BASEPATH to local directory
trees.

Steve Hathaway
